### ISSUE TITLE
remove swappable examples and only showcase contracts under `./contracts/recommended` 

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aex141-nft-collection-example#14]
## TODOs
- [x] remove everything related to swappable
- [x] move the contracts in the `recommended` to the upper folder
- [x] remove the `recommended` folder
- [x] make sure all tests for the recommended contracts are still passing

**Comment by marc0olo** [comment]
closed via https://github.com/aeternity/aex141-nft-collection-example/commit/a959d2dc4ceb5a8e1d125214d1bdd6c66d8889d4
