### ISSUE TITLE
refactor tests for NFT contracts

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aex141-nft-collection-example#15]
## Goal
It should be possible to execute any test without depending on another test. Currently tests rely on execution of other tests.

## Todos
- [ ] use snapshot feature after contract deployment
- [ ] provide a re-usable mint function that needs to be executed in each test-case
- [ ] perform a rollback after each test
